Improving how development environment is set up:
* Renamed "rake setup_dev" to "rake dev:setup"
* Added "rake dev:clean" and "rake dev:redo"
* Ensure rake is in the Gemfile
* Updated to use only jruby-complete jar, no more tgz

diff --git a/bin/bundle b/bin/bundle
--- a/bin/bundle
+++ b/bin/bundle
@@ -3,11 +3,10 @@
 dir=`dirname $0`
 . $dir/constants.sh
 
-find $VENDOR -name bundle | grep bundle > /dev/null
-if [ $? -eq 1 ] ; then
-  ./$dir/jruby -S gem install bundler
+BUNDLER=$GEM_HOME/bin/bundle
+if [ -f $BUNDLER ] ; then
+  ./$dir/jruby $BUNDLER $@
+else
+  echo "Cannot find bundler"
+  exit 1
 fi
-
-pushd $dir/../ > /dev/null
-./bin/jruby -S bundle $@
-popd > /dev/null
diff --git a/bin/compass b/bin/compass
--- a/bin/compass
+++ b/bin/compass
@@ -3,8 +3,10 @@
 dir=`dirname $0`
 . $dir/constants.sh
 
-find $VENDOR -name compass | grep compass > /dev/null
-if [ $? -eq 1 ] ; then 
-  ./$dir/bundle
+COMPASS=$GEM_HOME/bin/compass
+if [ -f $COMPASS ] ; then
+  ./$dir/jruby $COMPASS $@
+else
+  echo "Cannot find compass"
+  exit 1
 fi
-./$dir/jruby $JRUBY_DIR/lib/ruby/gems/1.8/bin/compass $@
diff --git a/bin/rake b/bin/rake
--- a/bin/rake
+++ b/bin/rake
@@ -3,8 +3,10 @@
 dir=`dirname $0`
 . $dir/constants.sh
 
-find $VENDOR -name rake | grep rake > /dev/null
-if [ $? -eq 1 ] ; then 
-  echo "You do not have rake installed in your JRuby installation. Please re-run: rake setup_dev"
+RAKE=$GEM_HOME/bin/rake
+if [ -f $RAKE ] ; then
+  ./$dir/jruby $RAKE $@
+else
+  echo "Cannot find rake"
+  exit 1
 fi
-$dir/jruby -S $GEM_HOME/bin/rake $@
diff --git a/bin/staticmatic b/bin/staticmatic
--- a/bin/staticmatic
+++ b/bin/staticmatic
@@ -3,8 +3,10 @@
 dir=`dirname $0`
 . $dir/constants.sh
 
-find $VENDOR -name staticmatic | grep staticmatic > /dev/null
-if [ $? -eq 1 ] ; then 
-  ./$dir/bundle
+STATIC_MATIC=$GEM_HOME/bin/staticmatic
+if [ -f $STATIC_MATIC ] ; then
+  ./$dir/jruby $STATIC_MATIC $@
+else
+  echo "Cannot find staticmatic"
+  exit 1
 fi
-./$dir/jruby $dir/../site/vendor/jruby-1.6.3/lib/ruby/gems/1.8/bin/staticmatic $@
